Added name and version options to venv command

diff --git a/scripts/venv b/scripts/venv
--- a/scripts/venv
+++ b/scripts/venv
@@ -5,18 +5,30 @@
 
 VENV_NAME=".venv"
 VENV_DEPS="requirements.txt"
+PYTHON_VERSION="3"
+
+# Help
+if [ "$1" = "help" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+    echo "Usage: venv [name?] [version?]"
+    echo "   name: The name of the virtual environment folder. Default: $VENV_NAME"
+    echo "   version: The version of python to use. Default: $PYTHON_VERSION"
+    exit 0
+fi
+
+# Assign parameters
+if [ ! -z $1 ]; then
+    VENV_NAME=$1
+fi
+if [ ! -z $1 ]; then
+    PYTHON_VERSION=$1
+fi
 
 # Check python installation and create venv
 echo "Creating virtual environment... ($VENV_NAME/)"
-if python --version > /dev/null; then # python
-    python -m venv "$VENV_NAME"
-elif python3 --version > /dev/null; then # python3
-    python3 -m venv "$VENV_NAME"
-elif py --version > /dev/null; then # py
-    py -m venv "$VENV_NAME"
-else
-    echo "Error: Could not find python runtime."
-    return 1
+python$PYTHON_VERSION -m venv "$VENV_NAME"
+if [ $? -ne 0 ]; then
+    echo "Failed to create virtual environment."
+    exit 1
 fi
 
 # Install packages with pip
